const en = {
  tabs: {
    home: 'Home',
    library: 'Library',
    collection: 'Collection',
    profile: 'Profile',
    admin: 'Admin',
  },
  home: {
    title: 'Khanqah Maseeh-ul-Ummah',
    subtitle: 'Hazrat Mufti Abdur Rasheed Miftahi DB',
    liveNow: 'Live Now',
    nextLive: 'Next Live',
    latestBayans: 'Latest Bayans',
    shortClips: 'Short Clips',
    seeAll: 'See All',
    join: 'Join',
  },
  library: {
    title: 'Library',
    search: 'Search bayans, clips, books…',
    bayans: 'Bayans',
    clips: 'Clips',
    nazams: 'Nazams',
    quran: 'Quran',
    hamdNaat: 'Hamd & Naat',
    books: 'Books',
  },
  collection: {
    title: 'My Collection',
    continueListen: 'Continue Listening',
    playlists: 'Playlists',
    downloads: 'Downloads',
    history: 'History',
    favourites: 'Favourites',
    newPlaylist: 'New Playlist',
    remaining: 'remaining',
    itemsOffline: 'items offline',
  },
  profile: {
    title: 'Profile',
    language: 'Language',
    theme: 'Theme',
    playbackSpeed: 'Playback Speed',
    skipInterval: 'Skip Interval',
    notifications: 'Notifications',
    aboutKhanqah: 'About Khanqah',
    muftiBio: 'Mufti Bio',
    signOut: 'Sign Out',
  },
  player: {
    nowPlaying: 'Now Playing',
    topics: 'Topics',
    speed: 'Speed',
    save: 'Save',
    share: 'Share',
    queue: 'Queue',
    live: 'Live',
    listening: 'Listening',
  },
  admin: {
    title: 'Admin',
    goLive: 'Go Live',
    upload: 'Upload',
    content: 'Content',
    schedule: 'Schedule',
    team: 'Team',
    start: 'Start',
    stopBroadcasting: 'Stop Broadcasting',
    listeners: 'Listeners',
    duration: 'Duration',
    autoSave: 'Auto Save',
    sendNotification: 'Send Notification',
    publishContent: 'Publish Content',
    sessionTitle: 'Session Title',
    contentType: 'Content Type',
    titleEn: 'Title (English)',
    titleUr: 'Title (Urdu)',
    category: 'Category',
    mediaUrl: 'Media URL',
    thumbnail: 'Thumbnail',
    scheduleNew: 'Schedule New',
    inviteMember: 'Invite Member',
    recording: 'Recording',
  },
  auth: {
    signIn: 'Sign In',
    signUp: 'Sign Up',
    email: 'Email',
    password: 'Password',
    googleSignIn: 'Sign in with Google',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
  },
  common: {
    on: 'On',
    off: 'Off',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    back: 'Back',
    min: 'min',
    daysAgo: 'days ago',
  },
};

export default en;
