const en = {
  tabs: {
    home: 'Home',
    library: 'Library',
    collection: 'Collection',
    profile: 'Profile',
    admin: 'Admin',
    bayanaat: 'Bayanaat',
    clips: 'Clips',
    ashaar: 'Ashaar',
    books: 'Books',
  },
  home: {
    title: 'Khanqah Maseeh-ul-Ummah',
    subtitle: 'Hazrat Mufti Abdur Rasheed Miftahi Sahab',
    liveNow: 'Live Now',
    nextLive: 'Next Live',
    latestBayans: 'Latest Bayans',
    shortClips: 'Short Clips',
    seeAll: 'See All',
    join: 'Join',
    recents: 'Recents',
    noContent: 'No content yet.',
    quickActions: {
      mamulat: 'Mamulat',
      liveSessions: 'Live Sessions',
      salahTimings: 'Salah Timings',
      majlisTimings: 'Majlis Timings',
      exploreCategories: 'Explore Categories',
      askHazrat: 'Ask Hazrat',
    },
  },
  library: {
    title: 'Library',
    search: 'Search bayans, clips, books…',
    bayans: 'Bayans',
    clips: 'Clips',
    nazams: 'Nazams',
    quran: 'Quran',
    hamdNaat: 'Hamd & Naat',
    books: 'Books',
  },
  collection: {
    title: 'My Collection',
    continueListen: 'Continue Listening',
    continueListening: 'Resume listening',
    playlists: 'Playlists',
    downloads: 'Downloads',
    history: 'History',
    favourites: 'Favourites',
    newPlaylist: 'New Playlist',
    remaining: 'remaining',
    itemsOffline: 'items offline',
    nothingPlaying: 'Nothing playing yet',
    noPlaylists: 'No playlists yet',
    noDownloads: 'No downloads yet',
    noHistory: 'No listening history',
  },
  profile: {
    title: 'Profile',
    guest: 'Guest',
    language: 'Language',
    theme: 'Appearance',
    playbackSpeed: 'Playback Speed',
    skipInterval: 'Skip Interval',
    notifications: 'Notifications',
    aboutKhanqah: 'About the Khanqah',
    muftiBio: "Hazrat Mufti Abdur Rasheed Miftahi Sahab's Bio",
    signOut: 'Sign Out',
    signOutTitle: 'Sign Out',
    signOutMessage: 'Are you sure you want to sign out?',
    on: 'On',
  },
  player: {
    nowPlaying: 'Now Playing',
    topics: 'Topics',
    speed: 'Speed',
    save: 'Save',
    saved: 'Saved',
    share: 'Share',
    queue: 'Queue',
    live: 'Live',
    listening: 'Listening',
    loading: 'Loading…',
    downloading: 'Downloading…',
    shareUnavailable: 'Sharing unavailable on this device.',
    downloadFailed: 'Download failed',
    shareFailed: 'Share failed',
  },
  admin: {
    title: 'Admin',
    goLive: 'Go Live',
    upload: 'Upload',
    uploadContent: 'Upload Content',
    content: 'Content',
    manageContent: 'Manage Content',
    schedule: 'Schedule',
    scheduleSessions: 'Schedule Sessions',
    team: 'Team',
    manageTeam: 'Manage Team',
    profile: 'Profile',
    start: 'Start',
    stopBroadcasting: 'Stop Broadcasting',
    listeners: 'Listeners',
    duration: 'Duration',
    autoSave: 'Auto Save',
    sendNotification: 'Send Notification',
    publishContent: 'Publish Content',
    sessionTitle: 'Session Title',
    contentType: 'Content Type',
    titleEn: 'Title (English)',
    titleUr: 'Title (Urdu)',
    category: 'Category',
    mediaUrl: 'Media URL',
    thumbnail: 'Thumbnail',
    scheduleNew: 'Schedule New',
    inviteMember: 'Invite Member',
    recording: 'Recording',
  },
  auth: {
    signIn: 'Sign In',
    signUp: 'Sign Up',
    email: 'Email',
    password: 'Password',
    googleSignIn: 'Sign in with Google',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    signInTitle: 'Sign in',
    signInSubtitle: 'to access live sessions',
    googleButton: 'Continue with Google',
    continueAsGuest: 'Continue as guest',
  },
  errors: {
    network: 'Network error. Please try again.',
    permissionMic: 'Microphone access denied. Open settings to allow.',
    permissionMicAction: 'Open Settings',
  },
  empty: {
    library: 'No items here yet.',
    recents: 'Your listening history is empty.',
  },
  comingSoon: {
    thisFeature: 'This feature',
    title: '{{name}} — coming soon',
    body: "We're working on this.",
    back: 'Back',
  },
  confirm: {
    cancel: 'Cancel',
    languageRestart: {
      title: 'Switch language?',
      body: 'The app needs to restart to apply.',
      ok: 'Restart',
    },
  },
  common: {
    on: 'On',
    off: 'Off',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    back: 'Back',
    min: 'min',
    daysAgo: 'days ago',
  },
};

export default en;
