const ur = {
  tabs: {
    home: 'ہوم',
    library: 'لائبریری',
    collection: 'مجموعہ',
    profile: 'پروفائل',
    admin: 'ایڈمن',
  },
  home: {
    title: 'خانقاہ مسیح الامت',
    subtitle: 'حضرت مفتی عبدالرشید مفتاحی دامت برکاتہم',
    liveNow: 'ابھی لائیو',
    nextLive: 'اگلا لائیو',
    latestBayans: 'تازہ ترین بیانات',
    shortClips: 'مختصر کلپس',
    seeAll: 'سب دیکھیں',
    join: 'شامل ہوں',
  },
  library: {
    title: 'لائبریری',
    search: 'بیانات، کلپس، کتابیں تلاش کریں…',
    bayans: 'بیانات',
    clips: 'کلپس',
    nazams: 'نظامیں',
    quran: 'قرآن',
    hamdNaat: 'حمد و نعت',
    books: 'کتابیں',
  },
  collection: {
    title: 'میرا مجموعہ',
    continueListen: 'سننا جاری رکھیں',
    continueListening: 'سننا جاری رکھیں',
    playlists: 'پلے لسٹ',
    downloads: 'ڈاؤن لوڈز',
    history: 'تاریخ',
    favourites: 'پسندیدہ',
    newPlaylist: 'نئی پلے لسٹ',
    remaining: 'باقی',
    itemsOffline: 'آئٹمز آف لائن',
    nothingPlaying: 'ابھی کچھ نہیں چل رہا',
    noPlaylists: 'ابھی کوئی پلے لسٹ نہیں',
    noDownloads: 'ابھی کوئی ڈاؤن لوڈ نہیں',
    noHistory: 'سننے کی کوئی تاریخ نہیں',
  },
  profile: {
    title: 'پروفائل',
    guest: 'مہمان',
    language: 'زبان',
    theme: 'تھیم',
    playbackSpeed: 'پلے بیک کی رفتار',
    skipInterval: 'اسکپ وقفہ',
    notifications: 'اطلاعات',
    aboutKhanqah: 'خانقاہ کے بارے میں',
    muftiBio: 'حضرت مفتی عبدالرشید مفتاحی صاحب کا تعارف',
    signOut: 'سائن آوٹ',
    signOutTitle: 'سائن آوٹ',
    signOutMessage: 'کیا آپ واقعی سائن آوٹ کرنا چاہتے ہیں؟',
    on: 'آن',
  },
  player: {
    nowPlaying: 'ابھی چل رہا ہے',
    topics: 'موضوعات',
    speed: 'رفتار',
    save: 'محفوظ کریں',
    share: 'شیئر کریں',
    queue: 'قطار',
    live: 'لائیو',
    listening: 'سن رہے ہیں',
  },
  admin: {
    title: 'ایڈمن',
    goLive: 'لائیو جائیں',
    upload: 'اپ لوڈ',
    content: 'مواد',
    schedule: 'شیڈول',
    team: 'ٹیم',
    start: 'شروع کریں',
    stopBroadcasting: 'نشریات بند کریں',
    listeners: 'سامعین',
    duration: 'مدت',
    autoSave: 'خودکار محفوظ',
    sendNotification: 'اطلاع بھیجیں',
    publishContent: 'مواد شائع کریں',
    sessionTitle: 'سیشن کا عنوان',
    contentType: 'مواد کی قسم',
    titleEn: 'عنوان (انگریزی)',
    titleUr: 'عنوان (اردو)',
    category: 'زمرہ',
    mediaUrl: 'میڈیا URL',
    thumbnail: 'تھمب نیل',
    scheduleNew: 'نیا شیڈول',
    inviteMember: 'رکن مدعو کریں',
    recording: 'ریکارڈنگ',
  },
  auth: {
    signIn: 'سائن ان',
    signUp: 'سائن اپ',
    email: 'ای میل',
    password: 'پاس ورڈ',
    googleSignIn: 'گوگل سے سائن ان کریں',
    noAccount: 'اکاؤنٹ نہیں ہے؟',
    haveAccount: 'پہلے سے اکاؤنٹ ہے؟',
  },
  common: {
    on: 'آن',
    off: 'آف',
    cancel: 'منسوخ',
    save: 'محفوظ کریں',
    delete: 'حذف کریں',
    edit: 'ترمیم',
    back: 'واپس',
    min: 'منٹ',
    daysAgo: 'دن پہلے',
  },
};

export default ur;
