const ur = {
  tabs: {
    home: 'ہوم',
    library: 'لائبریری',
    collection: 'مجموعہ',
    profile: 'پروفائل',
    admin: 'ایڈمن',
    bayanaat: 'بیانات',
    clips: 'کلپس',
    ashaar: 'اشعار',
    books: 'کتابیں',
  },
  home: {
    title: 'خانقاہ مسیح الامت',
    subtitle: 'حضرت مفتی عبدالرشید مفتاحی دامت برکاتہم',
    liveNow: 'ابھی لائیو',
    nextLive: 'اگلا لائیو',
    latestBayans: 'تازہ ترین بیانات',
    shortClips: 'مختصر کلپس',
    seeAll: 'سب دیکھیں',
    join: 'شامل ہوں',
    recents: 'تازہ ترین',
    noContent: 'ابھی تک کوئی مواد نہیں۔',
    quickActions: {
      mamulat: 'معمولات',
      liveSessions: 'لائیو سیشنز',
      salahTimings: 'اوقاتِ نماز',
      majlisTimings: 'اوقاتِ مجلس',
      exploreCategories: 'تمام زمرے',
      askHazrat: 'حضرت سے سوال',
    },
  },
  library: {
    title: 'لائبریری',
    search: 'بیانات، کلپس، کتابیں تلاش کریں…',
    bayans: 'بیانات',
    clips: 'کلپس',
    nazams: 'نظامیں',
    quran: 'قرآن',
    hamdNaat: 'حمد و نعت',
    books: 'کتابیں',
  },
  collection: {
    title: 'میرا مجموعہ',
    continueListen: 'سننا جاری رکھیں',
    continueListening: 'سننا جاری رکھیں',
    playlists: 'پلے لسٹ',
    downloads: 'ڈاؤن لوڈز',
    history: 'تاریخ',
    favourites: 'پسندیدہ',
    newPlaylist: 'نئی پلے لسٹ',
    remaining: 'باقی',
    itemsOffline: 'آئٹمز آف لائن',
    nothingPlaying: 'ابھی کچھ نہیں چل رہا',
    noPlaylists: 'ابھی کوئی پلے لسٹ نہیں',
    noDownloads: 'ابھی کوئی ڈاؤن لوڈ نہیں',
    noHistory: 'سننے کی کوئی تاریخ نہیں',
  },
  profile: {
    title: 'پروفائل',
    guest: 'مہمان',
    language: 'زبان',
    theme: 'تھیم',
    playbackSpeed: 'پلے بیک کی رفتار',
    skipInterval: 'اسکپ وقفہ',
    notifications: 'اطلاعات',
    aboutKhanqah: 'خانقاہ کے بارے میں',
    muftiBio: 'حضرت مفتی عبدالرشید مفتاحی صاحب کا تعارف',
    signOut: 'سائن آوٹ',
    signOutTitle: 'سائن آوٹ',
    signOutMessage: 'کیا آپ واقعی سائن آوٹ کرنا چاہتے ہیں؟',
    on: 'آن',
  },
  player: {
    nowPlaying: 'ابھی چل رہا ہے',
    topics: 'موضوعات',
    speed: 'رفتار',
    save: 'محفوظ کریں',
    saved: 'محفوظ شدہ',
    share: 'شیئر کریں',
    queue: 'قطار',
    live: 'لائیو',
    listening: 'سن رہے ہیں',
    loading: 'لوڈ ہو رہا ہے…',
    downloading: 'ڈاؤن لوڈ ہو رہا ہے…',
    shareUnavailable: 'اس آلے پر شیئرنگ دستیاب نہیں۔',
    downloadFailed: 'ڈاؤن لوڈ ناکام',
    shareFailed: 'شیئرنگ ناکام',
  },
  admin: {
    title: 'ایڈمن',
    goLive: 'لائیو جائیں',
    upload: 'اپ لوڈ',
    uploadContent: 'مواد اپ لوڈ کریں',
    content: 'مواد',
    manageContent: 'مواد کا انتظام',
    schedule: 'شیڈول',
    scheduleSessions: 'سیشنز شیڈول کریں',
    team: 'ٹیم',
    manageTeam: 'ٹیم کا انتظام',
    profile: 'پروفائل',
    start: 'شروع کریں',
    stopBroadcasting: 'نشریات بند کریں',
    listeners: 'سامعین',
    duration: 'مدت',
    autoSave: 'خودکار محفوظ',
    sendNotification: 'اطلاع بھیجیں',
    publishContent: 'مواد شائع کریں',
    sessionTitle: 'سیشن کا عنوان',
    contentType: 'مواد کی قسم',
    titleEn: 'عنوان (انگریزی)',
    titleUr: 'عنوان (اردو)',
    category: 'زمرہ',
    mediaUrl: 'میڈیا URL',
    thumbnail: 'تھمب نیل',
    scheduleNew: 'نیا شیڈول',
    inviteMember: 'رکن مدعو کریں',
    recording: 'ریکارڈنگ',
  },
  auth: {
    signIn: 'سائن ان',
    signUp: 'سائن اپ',
    email: 'ای میل',
    password: 'پاس ورڈ',
    googleSignIn: 'گوگل سے سائن ان کریں',
    noAccount: 'اکاؤنٹ نہیں ہے؟',
    haveAccount: 'پہلے سے اکاؤنٹ ہے؟',
    signInTitle: 'سائن اِن',
    signInSubtitle: 'لائیو سیشنز کے لیے',
    googleButton: 'گوگل سے جاری رکھیں',
    continueAsGuest: 'مہمان کے طور پر جاری رکھیں',
  },
  errors: {
    network: 'نیٹ ورک کی خرابی۔ دوبارہ کوشش کریں۔',
    permissionMic: 'مائیکروفون کی اجازت نہیں ہے۔ ترتیبات میں جا کر اجازت دیں۔',
    permissionMicAction: 'ترتیبات کھولیں',
  },
  empty: {
    library: 'یہاں ابھی کوئی آئٹم نہیں۔',
    recents: 'آپ کی سننے کی تاریخ خالی ہے۔',
  },
  comingSoon: {
    thisFeature: 'یہ خصوصیت',
    title: '{{name}} — جلد آرہا ہے',
    body: 'ہم اس پر کام کر رہے ہیں۔',
    back: 'واپس',
  },
  liveStatus: {
    onAir: 'لائیو',
    offAir: 'بند',
    offAirNext: 'بند · اگلی مجلس',
    noSessions: 'کوئی سیشن طے نہیں',
    liveSession: 'لائیو سیشن',
    majlis: 'مجلس',
    tapToJoin: 'شامل ہونے کے لیے ٹیپ کریں',
    startingSoon: 'جلد شروع ہو رہا ہے',
    inMinutes: '{{m}} منٹ میں',
    inHours: '{{h}} گھنٹے میں',
  },
  confirm: {
    cancel: 'منسوخ',
    languageRestart: {
      title: 'زبان تبدیل کریں؟',
      body: 'تبدیلی لاگو کرنے کے لیے ایپ کو دوبارہ شروع کرنا ہوگا۔',
      ok: 'دوبارہ شروع کریں',
    },
  },
  common: {
    on: 'آن',
    off: 'آف',
    cancel: 'منسوخ',
    save: 'محفوظ کریں',
    delete: 'حذف کریں',
    edit: 'ترمیم',
    back: 'واپس',
    min: 'منٹ',
    daysAgo: 'دن پہلے',
  },
};

export default ur;
